[package]
name = "texcomplete"
version = "1.0.1"
authors = ["hecal3 <hecal3@users.noreply.github.com>"]


[lib]
name = "texparser"
path = "src/lib.rs"

[[bin]]
name = "texcomplete"
path = "src/main.rs"

[dependencies]
glob = "0.2"
clap = "2.19"
regex = "0.1.80"
rustc-serialize = "0.3.22"
